<?php require_once __DIR__.'/../includes/business-header.php';$lesson=business_lesson($pdo,(int)($_GET['id']??0));if(!$lesson){http_response_code(404);exit('Lesson not found.');}$all=business_lessons($pdo,(int)$lesson['course_id']);$activities=business_activities($pdo,(int)$lesson['id']);$quiz=business_quiz($pdo,(int)$lesson['id']);$index=0;foreach($all as $i=>$row)if((int)$row['id']===(int)$lesson['id'])$index=$i;$prev=$all[$index-1]??null;$next=$all[$index+1]??null;if($_SERVER['REQUEST_METHOD']==='POST'&&verify_csrf($_POST['csrf_token']??null)&&learner_logged_in()){mark_business_progress($pdo,learner_id(),(int)$lesson['course_id'],(int)$lesson['id'],null);$cert=issue_business_certificate($pdo,learner_id(),(int)$lesson['course_id']);header('Location: lesson.php?id='.(int)$lesson['id'].'&complete=1'.($cert?'&certificate=1':''));exit;}$percent=count($all)?(int)round(($index+1)*100/count($all)):0;$steps=business_json($lesson['learning_steps']);?>
<div class="business-lesson-bar"><a class="biz-brand" href="<?=business_url('index.php')?>"><span>MD</span><div>Business AI <b>Academy</b></div></a><div><small>PROGRAM PROGRESS · <?=$percent?>%</small><div class="biz-progress"><i style="width:<?=$percent?>%"></i></div></div><a href="<?=business_url('course.php?slug='.urlencode($lesson['course_slug']))?>">Close ×</a></div>
<article class="business-lesson"><header class="lesson-heading"><div><span class="biz-eyebrow"><?=e($lesson['course_title'])?> · Lesson <?=$index+1?></span><h1><?=e($lesson['title'])?></h1><p><?=e($lesson['duration'])?> · Case study + practical activities</p></div><div class="coach-intro"><?php if($lesson['avatar_path']):?><img src="<?=e(site_url($lesson['avatar_path']))?>" alt="Business coach avatar"><?php else:?><span>◈</span><?php endif?><div><small>YOUR BUSINESS COACH</small><b>Strategy into action</b></div></div></header>
<section class="case-study"><div class="case-label"><span>NAIROBI BUSINESS CASE</span><b>01</b></div><h2><?=e($lesson['case_study_title'])?></h2><p><?=nl2br(e($lesson['case_study_text']))?></p></section>
<?php if($lesson['animation_type']==='lottie'&&$lesson['animation_source']):?><div class="biz-media"><lottie-player src="<?=e($lesson['animation_source'])?>" background="transparent" speed="1" loop autoplay></lottie-player></div><?php elseif($lesson['animation_type']==='video'&&($lesson['media_path']||$lesson['animation_source'])):?><video class="biz-video" controls preload="metadata" src="<?=e($lesson['media_path']?site_url($lesson['media_path']):$lesson['animation_source'])?>"></video><?php elseif($lesson['animation_type']==='image'&&$lesson['media_path']):?><img class="biz-video" src="<?=e(site_url($lesson['media_path']))?>" alt="Business lesson illustration"><?php else:?><?=business_visual($lesson['animation_type'])?><?php endif?>
<section class="business-steps"><div class="lesson-section-title"><span>STEP-BY-STEP</span><h2>Turn the case into a repeatable approach.</h2></div><div><?php foreach($steps as $i=>$step):?><article class="business-step reveal"><span><?=str_pad((string)($i+1),2,'0',STR_PAD_LEFT)?></span><div><h3><?=e($step['title']??'Business step')?></h3><p><?=e($step['text']??'')?></p></div></article><?php endforeach?></div></section>
<section class="business-tools"><div class="checklist-panel"><span>BUSINESS CHECKLIST</span><h2>Before you put AI to work</h2><?php foreach(preg_split('/\r?\n/',(string)$lesson['business_checklist']) as $item):if(trim($item)!==''):?><label><input type="checkbox"><i></i><?=e(trim($item))?></label><?php endif;endforeach?></div><div class="template-panel"><span>TAKE IT TO WORK</span><h2>Downloadable template</h2><p>Use this resource to plan and review the workflow with your team.</p><?php if($lesson['template_path']):?><a class="biz-btn gold" download href="<?=e(site_url($lesson['template_path']))?>">Download <?=e($lesson['template_label']?:'template')?> ↓</a><?php else:?><button class="biz-btn ghost" disabled>Template coming soon</button><?php endif?></div></section>
<section class="practical-block"><div class="lesson-section-title"><span>PRACTICAL APPLICATION</span><h2>Make the decisions yourself.</h2></div><div class="business-activity-grid"><?php foreach($activities as $activity):?><a href="<?=business_url('activity.php?id='.(int)$activity['id'])?>"><span><?=['matching'=>'↔','prompt'=>'✦','decision'=>'▥','risk'=>'◇'][$activity['activity_type']]??'◆'?></span><small><?=e(strtoupper($activity['activity_type']))?></small><h3><?=e($activity['title'])?></h3><p><?=e($activity['instructions'])?></p><b>Open activity ↗</b></a><?php endforeach?></div></section>
<section class="lesson-complete"><div><span>CAPABILITY CHECKPOINT</span><h2>Ready to record this lesson?</h2><p>Complete the activities and quiz, then save your progress toward the course certificate.</p></div><?php if($quiz):?><a class="biz-btn ghost" href="<?=business_url('quiz.php?lesson='.(int)$lesson['id'])?>">Take lesson quiz</a><?php endif?><?php if(learner_logged_in()):?><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><button class="biz-btn gold">Complete lesson ✓</button></form><?php else:?><a class="biz-btn gold" href="<?=site_url('academy/login.php')?>">Login to save progress</a><?php endif?></section>
<nav class="business-lesson-nav"><?php if($prev):?><a href="<?=business_url('lesson.php?id='.(int)$prev['id'])?>">← Previous case</a><?php else:?><span></span><?php endif?><?php if($next):?><a href="<?=business_url('lesson.php?id='.(int)$next['id'])?>">Next case →</a><?php else:?><a href="<?=business_url('course.php?slug='.urlencode($lesson['course_slug']))?>">Program overview →</a><?php endif?></nav></article>
<?php include __DIR__.'/../includes/business-footer.php';?>
