<?php
require_once __DIR__ . '/../includes/academy-header.php'; require_learner();
$courseId=(int)($_GET['course'] ?? 0); $lessonId=(int)($_GET['lesson'] ?? 0);
if (!$courseId && $lessonId) { $tmp=get_lesson($pdo,$lessonId); $courseId=(int)$tmp['course_id']; }
$course=get_course($pdo,$courseId); if(!$course){ exit('Course not found'); }
enroll_learner($pdo, learner_id(), $courseId); $lessons=get_course_lessons($pdo,$courseId); if(!$lessonId && $lessons){ $lessonId=(int)$lessons[0]['id']; } $lesson=get_lesson($pdo,$lessonId); if(!$lesson){ exit('Lesson not found'); }
if($_SERVER['REQUEST_METHOD']==='POST' && verify_csrf($_POST['csrf_token'] ?? null)){ mark_lesson_complete($pdo, learner_id(), $courseId, $lessonId); header('Location: lesson.php?course='.$courseId.'&lesson='.$lessonId.'&done=1'); exit; }
$progress=course_progress($pdo, learner_id(), $courseId);
?>
<section class="lesson-shell"><aside class="lesson-sidebar"><a class="brand-mark mb-4" href="dashboard.php"><img class="logo-mark" src="<?= site_url('assets/images/mugah-deeptech-logo.svg'); ?>" alt=""><span class="brand-text">Academy</span></a><h3><?= e($course['title']); ?></h3><div class="progress academy-progress mb-3"><div style="width: <?= $progress['percent']; ?>%"></div></div><?php foreach($lessons as $i=>$row): ?><a class="lesson-link <?= (int)$row['id']===$lessonId?'active':''; ?>" href="lesson.php?course=<?= $courseId; ?>&lesson=<?= (int)$row['id']; ?>"><span><?= $i+1; ?></span><?= e($row['title']); ?></a><?php endforeach; ?><a class="btn btn-premium w-100 mt-3" href="quiz.php?course=<?= $courseId; ?>">Take Quiz</a></aside><article class="lesson-content"><p class="eyebrow"><?= e($lesson['module_title']); ?></p><h1><?= e($lesson['title']); ?></h1><div class="video-placeholder">Video lesson placeholder</div><div class="glass-card"><h2>Lesson Notes</h2><p><?= nl2br(e($lesson['content'])); ?></p><h3>Downloadable Resources</h3><p><?= e($lesson['resource_url'] ?: 'Worksheet, reading list, and practice dataset will appear here for enrolled learners.'); ?></p><h3>Practical Assignment</h3><p><?= e($lesson['assignment_instructions']); ?></p><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()); ?>"><button class="btn btn-premium" type="submit">Mark as Complete</button></form></div></article></section>