<?php
$cmsAdminTitle='Course Card Presentation';require_once __DIR__.'/../includes/cms-admin-header.php';$pathway=(string)($_GET['pathway']??'Kids');if(!in_array($pathway,['Kids','Business','General'],true))$pathway='Kids';
if($_SERVER['REQUEST_METHOD']==='POST'&&verify_csrf($_POST['csrf_token']??null)){$id=(int)$_POST['id'];$pdo->prepare('UPDATE course_card_settings SET category=?,media_id=?,animation_url=?,price_type=?,price=?,button_text=?,sort_order=?,is_active=? WHERE id=?')->execute([trim((string)$_POST['category']),(int)$_POST['media_id']?:null,trim((string)$_POST['animation_url']),$_POST['price_type']==='Paid'?'Paid':'Free',(float)$_POST['price'],trim((string)$_POST['button_text']),max(1,(int)$_POST['sort_order']),isset($_POST['is_active'])?1:0,$id]);header('Location: academy-course-cards.php?pathway='.urlencode($pathway));exit;}
$media=cms_media_options($pdo);$edit=null;if(!empty($_GET['edit'])){$s=$pdo->prepare('SELECT * FROM course_card_settings WHERE id=?');$s->execute([(int)$_GET['edit']]);$edit=$s->fetch();}
if($pathway==='Kids')$sql="SELECT d.*,c.title,c.short_description description,c.difficulty level,c.duration FROM course_card_settings d JOIN kids_courses c ON c.id=d.course_id WHERE d.pathway='Kids'";elseif($pathway==='Business')$sql="SELECT d.*,c.title,c.short_description description,c.level,c.duration FROM course_card_settings d JOIN business_courses c ON c.id=d.course_id WHERE d.pathway='Business'";else $sql="SELECT d.*,c.title,c.short_description description,c.level,c.duration FROM course_card_settings d JOIN lms_courses c ON c.id=d.course_id WHERE d.pathway='General'";$rows=$pdo->query($sql.' ORDER BY d.sort_order,d.id')->fetchAll();$courseAdmin=$pathway==='Kids'?'kids-courses.php':($pathway==='Business'?'business-courses.php':'lms-courses.php');
?>
<div class="admin-top"><div><p class="eyebrow">Cards shown on frontend</p><h1>Course Card Presentation</h1></div><a class="btn btn-outline-light" href="<?=e($courseAdmin)?>">Edit course content</a></div><div class="d-flex gap-2 mb-4"><?php foreach(['Kids','Business','General'] as $v):?><a class="btn <?=$pathway===$v?'btn-premium':'btn-outline-light'?>" href="?pathway=<?=$v?>"><?=$v?></a><?php endforeach?></div>
<?php if($edit):?><form class="glass-card cms-form mb-4" method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=(int)$edit['id']?>"><label>Category<input class="form-control" name="category" value="<?=e($edit['category'])?>"></label><label>Button text<input class="form-control" name="button_text" value="<?=e($edit['button_text'])?>"></label><label>Media<select class="form-select" name="media_id"><option value="0">No thumbnail</option><?php foreach($media as $m):?><option value="<?=(int)$m['id']?>" <?=(int)$edit['media_id']===(int)$m['id']?'selected':''?>><?=e($m['title'])?></option><?php endforeach?></select></label><label>Animation URL<input class="form-control" name="animation_url" value="<?=e($edit['animation_url'])?>"></label><label>Price type<select class="form-select" name="price_type"><option>Free</option><option <?=$edit['price_type']==='Paid'?'selected':''?>>Paid</option></select></label><label>Price<input class="form-control" type="number" step="0.01" name="price" value="<?=e((string)$edit['price'])?>"></label><label>Display order<input class="form-control" type="number" name="sort_order" value="<?=(int)$edit['sort_order']?>"></label><label><input type="checkbox" name="is_active" value="1" <?=$edit['is_active']?'checked':''?>> Visible card</label><div class="wide"><button class="btn btn-premium">Save card settings</button></div></form><?php endif?>
<div class="glass-card table-responsive"><table class="table table-dark"><tr><th>Order</th><th>Course</th><th>Category</th><th>Level / Duration</th><th>Price</th><th>Visible</th><th></th></tr><?php foreach($rows as $row):?><tr><td><?=(int)$row['sort_order']?></td><td><strong><?=e($row['title'])?></strong><small class="d-block text-secondary"><?=e(mb_strimwidth($row['description'],0,80,'…'))?></small></td><td><?=e($row['category'])?></td><td><?=e($row['level'].' · '.$row['duration'])?></td><td><?=e($row['price_type'])?></td><td><?=$row['is_active']?'Yes':'No'?></td><td><a class="btn btn-sm btn-outline-light" href="?pathway=<?=$pathway?>&edit=<?=(int)$row['id']?>">Edit card</a></td></tr><?php endforeach?></table></div>
<?php require_once __DIR__.'/../includes/cms-admin-footer.php';?>