<?php
$cmsAdminTitle='Academy Media Library';require_once __DIR__.'/../includes/cms-admin-header.php';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'&&verify_csrf($_POST['csrf_token']??null)){try{$action=(string)($_POST['action']??'upload');$id=(int)($_POST['id']??0);if($action==='delete'){cms_require_delete_role();$pdo->prepare('DELETE FROM media_library WHERE id=?')->execute([$id]);}elseif($action==='toggle'){$pdo->prepare('UPDATE media_library SET is_active=1-is_active WHERE id=?')->execute([$id]);}elseif($action==='update'){$pdo->prepare('UPDATE media_library SET title=?,alt_text=? WHERE id=?')->execute([trim((string)$_POST['title']),trim((string)$_POST['alt_text']),$id]);}else{$file=cms_admin_upload('media_file');if(!$file)throw new RuntimeException('Choose a file to upload.');$pdo->prepare('INSERT INTO media_library (title,file_path,file_type,mime_type,file_size,alt_text,uploaded_by) VALUES (?,?,?,?,?,?,?)')->execute([trim((string)$_POST['title']),$file['path'],$file['type'],$file['mime'],$file['size'],trim((string)$_POST['alt_text']),(int)($_SESSION['admin_id']??0)]);}header('Location: academy-media.php?saved=1');exit;}catch(Throwable $e){$error=$e->getMessage();}}
$edit=null;if(!empty($_GET['edit'])){$s=$pdo->prepare('SELECT * FROM media_library WHERE id=?');$s->execute([(int)$_GET['edit']]);$edit=$s->fetch();}$rows=$pdo->query('SELECT * FROM media_library ORDER BY created_at DESC')->fetchAll();
?>
<div class="admin-top"><div><p class="eyebrow">Reusable assets</p><h1>Media Library</h1><p>Upload once, then assign the asset to heroes, pathways, components, course cards, avatars, or lesson blocks.</p></div></div><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif?>
<form class="glass-card cms-form mb-4" method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="upload"><label>Media title<input class="form-control" name="title" required></label><label>Alt text / accessible description<input class="form-control" name="alt_text"></label><label class="wide">File<input class="form-control" type="file" name="media_file" accept="image/*,video/mp4,application/json,audio/*,.pdf,.docx,.xlsx,.csv" required><small class="cms-help">Images, GIFs, MP4, Lottie JSON, MP3/WAV, PDFs, Word, Excel, and CSV up to 20 MB.</small></label><div class="wide"><button class="btn btn-premium">Upload to library</button></div></form>
<?php if($edit):?><form class="glass-card cms-form mb-4" method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="update"><input type="hidden" name="id" value="<?=(int)$edit['id']?>"><label>Title<input class="form-control" name="title" value="<?=e($edit['title'])?>"></label><label>Alt text<input class="form-control" name="alt_text" value="<?=e($edit['alt_text'])?>"></label><div><button class="btn btn-premium">Update metadata</button></div></form><?php endif?>
<div class="glass-card table-responsive"><table class="table table-dark align-middle"><tr><th>Preview</th><th>Asset</th><th>Type</th><th>Size</th><th>Active</th><th></th></tr><?php foreach($rows as $row):?><tr><td><?php if(in_array($row['file_type'],['image','gif'],true)):?><img class="cms-thumb" src="<?=e(site_url($row['file_path']))?>" alt=""><?php else:?><span class="tag"><?=e(strtoupper($row['file_type']))?></span><?php endif?></td><td><strong><?=e($row['title'])?></strong><small class="d-block text-secondary"><?=e($row['file_path'])?></small></td><td><?=e($row['mime_type'])?></td><td><?=number_format((int)$row['file_size']/1024,1)?> KB</td><td><?=$row['is_active']?'Yes':'No'?></td><td><a class="btn btn-sm btn-outline-light" href="?edit=<?=(int)$row['id']?>">Edit</a><form class="d-inline" method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=(int)$row['id']?>"><button class="btn btn-sm btn-outline-warning" name="action" value="toggle">Toggle</button><?php if(cms_can_delete()):?><button class="btn btn-sm btn-danger" name="action" value="delete" onclick="return confirm('Remove this library record? Existing files remain on disk for safety.')">Delete</button><?php endif?></form></td></tr><?php endforeach?></table></div>
<?php require_once __DIR__.'/../includes/cms-admin-footer.php';?>
