<?php
$adminTitle='Animated Kids Lessons';require_once __DIR__.'/../includes/kids-admin-header.php';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'&&verify_csrf($_POST['csrf_token']??null)){
 try{$action=(string)($_POST['action']??'save');$id=(int)($_POST['id']??0);if($action==='delete'&&$id){$pdo->prepare('DELETE FROM kids_lessons WHERE id=?')->execute([$id]);header('Location: kids-lessons.php');exit;}
 $media=kids_admin_upload('media');if(!$media)$media=trim((string)($_POST['existing_media']??''));$blocks=[];for($i=1;$i<=3;$i++){if(trim((string)($_POST['block_'.$i.'_title']??''))!=='')$blocks[]=['title'=>trim((string)$_POST['block_'.$i.'_title']),'text'=>trim((string)$_POST['block_'.$i.'_text'])];}
 $data=[(int)$_POST['course_id'],trim((string)$_POST['title']),slugify(trim((string)($_POST['slug']?:$_POST['title']))),trim((string)$_POST['story_title']),trim((string)$_POST['story_text']),json_encode($blocks,JSON_UNESCAPED_UNICODE),$_POST['animation_type'],trim((string)$_POST['animation_source']),trim((string)$_POST['narration_text']),$media,trim((string)$_POST['duration']),(int)$_POST['sort_order'],$_POST['status']==='Draft'?'Draft':'Published'];
 if($id){$data[]=$id;$pdo->prepare('UPDATE kids_lessons SET course_id=?,title=?,slug=?,story_title=?,story_text=?,learning_blocks=?,animation_type=?,animation_source=?,narration_text=?,media_path=?,duration=?,sort_order=?,status=? WHERE id=?')->execute($data);}else{$pdo->prepare('INSERT INTO kids_lessons (course_id,title,slug,story_title,story_text,learning_blocks,animation_type,animation_source,narration_text,media_path,duration,sort_order,status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute($data);}header('Location: kids-lessons.php?saved=1');exit;
 }catch(Throwable $e){$error=$e->getMessage();}
}
$edit=!empty($_GET['edit'])?kids_lesson($pdo,(int)$_GET['edit']):null;$showForm=$edit||isset($_GET['new']);$courses=kids_courses($pdo,false);$all=$pdo->query('SELECT l.*,c.title course_title FROM kids_lessons l JOIN kids_courses c ON c.id=l.course_id ORDER BY c.sort_order,l.sort_order')->fetchAll();$blocks=$edit?kids_learning_blocks($edit):[];
?>
<div class="admin-top"><div><p class="eyebrow">Kids Academy</p><h1>Animated Lessons</h1></div><a class="btn btn-premium" href="?new=1">Add lesson</a></div><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif?><?php if(isset($_GET['saved'])):?><div class="alert alert-success">Lesson saved.</div><?php endif?>
<?php if($showForm):?><form class="glass-card kids-admin-form mb-4" method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=(int)($edit['id']??0)?>"><input type="hidden" name="existing_media" value="<?=e($edit['media_path']??'')?>"><div class="wide"><h2><?=$edit?'Edit animated lesson':'Create animated lesson'?></h2></div><label>Course<select class="form-select" name="course_id" required><?php foreach($courses as $c):?><option value="<?=(int)$c['id']?>" <?=(int)($edit['course_id']??0)===(int)$c['id']?'selected':''?>><?=e($c['title'])?></option><?php endforeach?></select></label><label>Lesson title<input class="form-control" name="title" value="<?=e($edit['title']??'')?>" required></label><label>Slug<input class="form-control" name="slug" value="<?=e($edit['slug']??'')?>"></label><label>Story title<input class="form-control" name="story_title" value="<?=e($edit['story_title']??'')?>"></label><label class="wide">Story-based explanation<textarea class="form-control" name="story_text" required><?=e($edit['story_text']??'')?></textarea></label>
<?php for($i=1;$i<=3;$i++):$b=$blocks[$i-1]??[];?><label>Step <?=$i?> title<input class="form-control" name="block_<?=$i?>_title" value="<?=e($b['title']??'')?>"></label><label>Step <?=$i?> explanation<textarea class="form-control" name="block_<?=$i?>_text"><?=e($b['text']??'')?></textarea></label><?php endfor?>
<label>Animation type<select class="form-select" name="animation_type"><?php foreach(['robot','computer','code','safety','robotics','creative','lottie','video','image'] as $v):?><option <?=($edit['animation_type']??'robot')===$v?'selected':''?>><?=$v?></option><?php endforeach?></select></label><label>Lottie/video URL<input class="form-control" name="animation_source" value="<?=e($edit['animation_source']??'')?>"><small class="media-note">Use a trusted HTTPS Lottie JSON or short video URL.</small></label><label class="wide">Upload image, GIF, Lottie JSON, or MP4<input class="form-control" type="file" name="media" accept="image/jpeg,image/png,image/gif,image/webp,video/mp4,application/json"><small class="media-note">Maximum 8 MB. Current: <?=e($edit['media_path']??'none')?></small></label><label class="wide">Narration text<textarea class="form-control" name="narration_text"><?=e($edit['narration_text']??'')?></textarea></label><label>Duration<input class="form-control" name="duration" value="<?=e($edit['duration']??'10 minutes')?>"></label><label>Sort order<input class="form-control" type="number" min="1" name="sort_order" value="<?=(int)($edit['sort_order']??1)?>"></label><label>Status<select class="form-select" name="status"><option <?=($edit['status']??'Published')==='Published'?'selected':''?>>Published</option><option <?=($edit['status']??'')==='Draft'?'selected':''?>>Draft</option></select></label><div class="wide"><button class="btn btn-premium" name="action" value="save">Save lesson</button> <a class="btn btn-outline-light" href="kids-lessons.php">Cancel</a></div></form><?php endif?>
<div class="glass-card table-responsive"><table class="table table-dark align-middle"><thead><tr><th>Lesson</th><th>Course</th><th>Animation</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($all as $row):?><tr><td><strong><?=e($row['title'])?></strong><small class="d-block text-secondary"><?=e($row['duration'])?></small></td><td><?=e($row['course_title'])?></td><td><?=e($row['animation_type'])?></td><td><?=e($row['status'])?></td><td class="text-end"><a class="btn btn-sm btn-outline-light" href="?edit=<?=(int)$row['id']?>">Edit</a><form class="d-inline" method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=(int)$row['id']?>"><button class="btn btn-sm btn-danger" name="action" value="delete" onclick="return confirm('Delete lesson?')">Delete</button></form></td></tr><?php endforeach?></tbody></table></div>
<?php require_once __DIR__.'/../includes/kids-admin-footer.php';?>
