<?php
$adminTitle='Kids Badges & Certificates';require_once __DIR__.'/../includes/kids-admin-header.php';$message='';
if($_SERVER['REQUEST_METHOD']==='POST'&&verify_csrf($_POST['csrf_token']??null)){
 $action=(string)$_POST['action'];
 if($action==='save_badge'){$id=(int)($_POST['id']??0);$data=[trim((string)$_POST['name']),slugify(trim((string)($_POST['slug']?:$_POST['name']))),trim((string)$_POST['description']),trim((string)$_POST['icon']),trim((string)$_POST['color']),trim((string)$_POST['criteria'])];if($id){$data[]=$id;$pdo->prepare('UPDATE badges SET name=?,slug=?,description=?,icon=?,color=?,criteria=? WHERE id=?')->execute($data);}else{$pdo->prepare('INSERT INTO badges (name,slug,description,icon,color,criteria) VALUES (?,?,?,?,?,?)')->execute($data);}}
 if($action==='delete_badge')$pdo->prepare('DELETE FROM badges WHERE id=?')->execute([(int)$_POST['id']]);
 if($action==='award_badge'){$pdo->prepare('INSERT IGNORE INTO learner_badges (learner_id,badge_id) VALUES (?,?)')->execute([(int)$_POST['learner_id'],(int)$_POST['badge_id']]);$message='Badge awarded.';}
 if($action==='award_certificate'){$code='KIDS-'.date('Y').'-'.strtoupper(substr(bin2hex(random_bytes(5)),0,10));$pdo->prepare('INSERT IGNORE INTO kids_certificates (learner_id,course_id,certificate_code,awarded_by) VALUES (?,?,?,?)')->execute([(int)$_POST['learner_id'],(int)$_POST['course_id'],$code,(int)($_SESSION['admin_id']??0)]);$message='Certificate awarded.';}
 if(!$message){header('Location: kids-badges.php?saved=1');exit;}
}
$edit=null;if(!empty($_GET['edit'])){$s=$pdo->prepare('SELECT * FROM badges WHERE id=?');$s->execute([(int)$_GET['edit']]);$edit=$s->fetch();}$badges=$pdo->query('SELECT b.*,COUNT(lb.id) awards FROM badges b LEFT JOIN learner_badges lb ON lb.badge_id=b.id GROUP BY b.id ORDER BY b.name')->fetchAll();$learners=$pdo->query('SELECT l.id,l.full_name,g.age_group FROM learners l JOIN kids_guardian_profiles g ON g.learner_id=l.id ORDER BY l.full_name')->fetchAll();$courses=kids_courses($pdo,false);$certs=$pdo->query('SELECT x.*,l.full_name,c.title course_title FROM kids_certificates x JOIN learners l ON l.id=x.learner_id JOIN kids_courses c ON c.id=x.course_id ORDER BY x.issued_at DESC')->fetchAll();
?>
<div class="admin-top"><div><p class="eyebrow">Kids Academy</p><h1>Badges & Certificates</h1></div><a class="btn btn-premium" href="?new=1">Create badge</a></div><?php if($message):?><div class="alert alert-success"><?=e($message)?></div><?php endif?>
<?php if($edit||isset($_GET['new'])):?><form class="glass-card kids-admin-form mb-4" method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save_badge"><input type="hidden" name="id" value="<?=(int)($edit['id']??0)?>"><label>Name<input class="form-control" name="name" value="<?=e($edit['name']??'')?>" required></label><label>Slug<input class="form-control" name="slug" value="<?=e($edit['slug']??'')?>"></label><label>Icon / emoji<input class="form-control" name="icon" value="<?=e($edit['icon']??'🏅')?>"></label><label>Color<input class="form-control form-control-color" type="color" name="color" value="<?=e($edit['color']??'#6757f5')?>"></label><label class="wide">Description<input class="form-control" name="description" value="<?=e($edit['description']??'')?>" required></label><label class="wide">Award criteria<input class="form-control" name="criteria" value="<?=e($edit['criteria']??'')?>"></label><div><button class="btn btn-premium">Save badge</button></div></form><?php endif?>
<div class="row g-4 mb-4"><div class="col-xl-6"><form class="glass-card" method="post"><h2>Award a badge</h2><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="award_badge"><select class="form-select mb-3" name="learner_id"><?php foreach($learners as $l):?><option value="<?=(int)$l['id']?>"><?=e($l['full_name'].' ('.$l['age_group'].')')?></option><?php endforeach?></select><select class="form-select mb-3" name="badge_id"><?php foreach($badges as $b):?><option value="<?=(int)$b['id']?>"><?=e($b['icon'].' '.$b['name'])?></option><?php endforeach?></select><button class="btn btn-premium">Award badge</button></form></div><div class="col-xl-6"><form class="glass-card" method="post"><h2>Award a certificate</h2><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="award_certificate"><select class="form-select mb-3" name="learner_id"><?php foreach($learners as $l):?><option value="<?=(int)$l['id']?>"><?=e($l['full_name'])?></option><?php endforeach?></select><select class="form-select mb-3" name="course_id"><?php foreach($courses as $c):?><option value="<?=(int)$c['id']?>"><?=e($c['title'])?></option><?php endforeach?></select><button class="btn btn-premium">Award certificate</button></form></div></div>
<div class="glass-card table-responsive mb-4"><h2>Badge library</h2><table class="table table-dark"><tr><th>Badge</th><th>Criteria</th><th>Awards</th><th></th></tr><?php foreach($badges as $b):?><tr><td><?=e($b['icon'].' '.$b['name'])?></td><td><?=e($b['criteria'])?></td><td><?=(int)$b['awards']?></td><td><a href="?edit=<?=(int)$b['id']?>">Edit</a></td></tr><?php endforeach?></table></div><div class="glass-card"><h2>Certificates issued</h2><?php foreach($certs as $c):?><p><strong><?=e($c['certificate_code'])?></strong> — <?=e($c['full_name'].' / '.$c['course_title'])?></p><?php endforeach?></div>
<?php require_once __DIR__.'/../includes/kids-admin-footer.php';?>
