<?php
$adminTitle='Manage Kids Courses';require_once __DIR__.'/../includes/kids-admin-header.php';$message='';
if($_SERVER['REQUEST_METHOD']==='POST'&&verify_csrf($_POST['csrf_token']??null)){
  $action=(string)($_POST['action']??'save');$id=(int)($_POST['id']??0);
  if($action==='delete'&&$id){$pdo->prepare('DELETE FROM kids_courses WHERE id=?')->execute([$id]);header('Location: kids-courses.php');exit;}
  $data=['title'=>trim((string)$_POST['title']),'slug'=>slugify(trim((string)($_POST['slug']?:$_POST['title']))),'short'=>trim((string)$_POST['short_description']),'description'=>trim((string)$_POST['description']),'age'=>in_array($_POST['age_group'],['6-8','9-12','13-15','All'],true)?$_POST['age_group']:'All','difficulty'=>trim((string)$_POST['difficulty']),'duration'=>trim((string)$_POST['duration']),'icon'=>trim((string)$_POST['icon']),'color'=>preg_match('/^#[0-9a-f]{6}$/i',(string)$_POST['theme_color'])?$_POST['theme_color']:'#6757f5','outcomes'=>trim((string)$_POST['learning_outcomes']),'status'=>$_POST['status']==='Draft'?'Draft':'Published','sort'=>(int)$_POST['sort_order']];
  if($id){$s=$pdo->prepare('UPDATE kids_courses SET title=:title,slug=:slug,short_description=:short,description=:description,age_group=:age,difficulty=:difficulty,duration=:duration,icon=:icon,theme_color=:color,learning_outcomes=:outcomes,status=:status,sort_order=:sort WHERE id=:id');$data['id']=$id;$s->execute(array_combine(array_map(fn($k)=>':'.$k,array_keys($data)),array_values($data)));}
  else{$s=$pdo->prepare('INSERT INTO kids_courses (title,slug,short_description,description,age_group,difficulty,duration,icon,theme_color,learning_outcomes,status,sort_order) VALUES (:title,:slug,:short,:description,:age,:difficulty,:duration,:icon,:color,:outcomes,:status,:sort)');$s->execute(array_combine(array_map(fn($k)=>':'.$k,array_keys($data)),array_values($data)));}
  header('Location: kids-courses.php?saved=1');exit;
}
$edit=!empty($_GET['edit'])?kids_course($pdo,(int)$_GET['edit']):null;$showForm=$edit||isset($_GET['new']);$courses=kids_courses($pdo,false);
?>
<div class="admin-top"><div><p class="eyebrow">Kids Academy</p><h1>Courses</h1></div><a class="btn btn-premium" href="kids-courses.php?new=1">Add course</a></div>
<?php if(isset($_GET['saved'])):?><div class="alert alert-success">Course saved.</div><?php endif?>
<?php if($showForm):?><form class="glass-card kids-admin-form mb-4" method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=(int)($edit['id']??0)?>"><div class="wide"><h2><?=$edit?'Edit course':'Create a kids course'?></h2></div><label>Title<input class="form-control" name="title" value="<?=e($edit['title']??'')?>" required></label><label>Slug<input class="form-control" name="slug" value="<?=e($edit['slug']??'')?>" placeholder="Generated from title"></label><label class="wide">Short child-friendly description<textarea class="form-control" name="short_description" required><?=e($edit['short_description']??'')?></textarea></label><label class="wide">Full description<textarea class="form-control" name="description" required><?=e($edit['description']??'')?></textarea></label><label>Age group<select class="form-select" name="age_group"><?php foreach(['6-8','9-12','13-15','All'] as $v):?><option <?=$v===($edit['age_group']??'All')?'selected':''?>><?=$v?></option><?php endforeach?></select></label><label>Difficulty<input class="form-control" name="difficulty" value="<?=e($edit['difficulty']??'Beginner')?>"></label><label>Duration<input class="form-control" name="duration" value="<?=e($edit['duration']??'6 lessons · 45 min')?>"></label><label>Animated icon / emoji<input class="form-control" name="icon" value="<?=e($edit['icon']??'🤖')?>"></label><label>Theme color<input class="form-control form-control-color" type="color" name="theme_color" value="<?=e($edit['theme_color']??'#6757f5')?>"></label><label>Sort order<input class="form-control" type="number" min="1" name="sort_order" value="<?=(int)($edit['sort_order']??1)?>"></label><label class="wide">Learning outcomes (one per line)<textarea class="form-control" name="learning_outcomes"><?=e($edit['learning_outcomes']??'')?></textarea></label><label>Status<select class="form-select" name="status"><option <?=($edit['status']??'Published')==='Published'?'selected':''?>>Published</option><option <?=($edit['status']??'')==='Draft'?'selected':''?>>Draft</option></select></label><div class="wide"><button class="btn btn-premium" name="action" value="save">Save course</button> <a class="btn btn-outline-light" href="kids-courses.php">Cancel</a></div></form><?php endif?>
<div class="glass-card table-responsive"><table class="table table-dark align-middle"><thead><tr><th>Course</th><th>Age</th><th>Duration</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($courses as $course):?><tr><td><span class="me-2 fs-4"><?=e($course['icon'])?></span><strong><?=e($course['title'])?></strong><small class="d-block text-secondary"><?=(int)$course['lesson_count']?> lessons</small></td><td><?=e($course['age_group'])?></td><td><?=e($course['duration'])?></td><td><?=e($course['status'])?></td><td class="text-end"><a class="btn btn-sm btn-outline-light" href="?edit=<?=(int)$course['id']?>">Edit</a><form class="d-inline" method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=(int)$course['id']?>"><button class="btn btn-sm btn-danger" name="action" value="delete" onclick="return confirm('Delete this course and all of its kids content?')">Delete</button></form></td></tr><?php endforeach?></tbody></table></div>
<?php require_once __DIR__.'/../includes/kids-admin-footer.php';?>
