<?php
$adminTitle='Kids Quizzes';require_once __DIR__.'/../includes/kids-admin-header.php';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'&&verify_csrf($_POST['csrf_token']??null)){
 try{$action=(string)$_POST['action'];$id=(int)($_POST['id']??0);
  if($action==='delete_quiz')$pdo->prepare('DELETE FROM kids_quizzes WHERE id=?')->execute([$id]);
  if($action==='delete_question')$pdo->prepare('DELETE FROM kids_quiz_questions WHERE id=?')->execute([$id]);
  if($action==='save_quiz'){$lesson=kids_lesson($pdo,(int)$_POST['lesson_id']);$data=[(int)$lesson['course_id'],(int)$lesson['id'],trim((string)$_POST['title']),(int)$_POST['pass_mark'],(int)$_POST['badge_id']?:null,$_POST['status']==='Draft'?'Draft':'Published'];if($id){$data[]=$id;$pdo->prepare('UPDATE kids_quizzes SET course_id=?,lesson_id=?,title=?,pass_mark=?,badge_id=?,status=? WHERE id=?')->execute($data);}else{$pdo->prepare('INSERT INTO kids_quizzes (course_id,lesson_id,title,pass_mark,badge_id,status) VALUES (?,?,?,?,?,?)')->execute($data);}}
  if($action==='save_question'){$options=array_values(array_filter(array_map('trim',preg_split('/\r?\n/',(string)$_POST['options']))));if(count($options)<2)throw new RuntimeException('Add at least two answer options, one per line.');if(!in_array(trim((string)$_POST['correct_answer']),$options,true))throw new RuntimeException('The correct answer must exactly match one option.');$data=[(int)$_POST['quiz_id'],trim((string)$_POST['question']),json_encode($options,JSON_UNESCAPED_UNICODE),trim((string)$_POST['correct_answer']),trim((string)$_POST['explanation']),(int)$_POST['sort_order']];if($id){$data[]=$id;$pdo->prepare('UPDATE kids_quiz_questions SET quiz_id=?,question=?,options_json=?,correct_answer=?,explanation=?,sort_order=? WHERE id=?')->execute($data);}else{$pdo->prepare('INSERT INTO kids_quiz_questions (quiz_id,question,options_json,correct_answer,explanation,sort_order) VALUES (?,?,?,?,?,?)')->execute($data);}}
  header('Location: kids-quizzes.php?saved=1');exit;
 }catch(Throwable $e){$error=$e->getMessage();}
}
$lessons=$pdo->query('SELECT l.id,l.title,c.title course_title FROM kids_lessons l JOIN kids_courses c ON c.id=l.course_id ORDER BY c.sort_order,l.sort_order')->fetchAll();$badges=$pdo->query('SELECT * FROM badges ORDER BY name')->fetchAll();$quizzes=$pdo->query('SELECT q.*,l.title lesson_title,c.title course_title,COUNT(x.id) question_count FROM kids_quizzes q JOIN kids_lessons l ON l.id=q.lesson_id JOIN kids_courses c ON c.id=q.course_id LEFT JOIN kids_quiz_questions x ON x.quiz_id=q.id GROUP BY q.id ORDER BY q.id DESC')->fetchAll();
$eq=null;if(!empty($_GET['edit_quiz'])){$s=$pdo->prepare('SELECT * FROM kids_quizzes WHERE id=?');$s->execute([(int)$_GET['edit_quiz']]);$eq=$s->fetch();}$question=null;if(!empty($_GET['edit_question'])){$s=$pdo->prepare('SELECT * FROM kids_quiz_questions WHERE id=?');$s->execute([(int)$_GET['edit_question']]);$question=$s->fetch();}$selected=(int)($_GET['quiz']??$question['quiz_id']??0);$questions=[];if($selected){$s=$pdo->prepare('SELECT * FROM kids_quiz_questions WHERE quiz_id=? ORDER BY sort_order,id');$s->execute([$selected]);$questions=$s->fetchAll();}
?>
<div class="admin-top"><div><p class="eyebrow">Kids Academy</p><h1>Quizzes & Questions</h1></div><a class="btn btn-premium" href="?new_quiz=1">Add quiz</a></div><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif?>
<?php if($eq||isset($_GET['new_quiz'])):?><form class="glass-card kids-admin-form mb-4" method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save_quiz"><input type="hidden" name="id" value="<?=(int)($eq['id']??0)?>"><label>Lesson<select class="form-select" name="lesson_id"><?php foreach($lessons as $l):?><option value="<?=(int)$l['id']?>" <?=(int)($eq['lesson_id']??0)===(int)$l['id']?'selected':''?>><?=e($l['course_title'].' — '.$l['title'])?></option><?php endforeach?></select></label><label>Quiz title<input class="form-control" name="title" value="<?=e($eq['title']??'')?>" required></label><label>Pass mark %<input class="form-control" type="number" min="1" max="100" name="pass_mark" value="<?=(int)($eq['pass_mark']??70)?>"></label><label>Reward badge<select class="form-select" name="badge_id"><option value="0">No badge</option><?php foreach($badges as $b):?><option value="<?=(int)$b['id']?>" <?=(int)($eq['badge_id']??0)===(int)$b['id']?'selected':''?>><?=e($b['icon'].' '.$b['name'])?></option><?php endforeach?></select></label><label>Status<select class="form-select" name="status"><option>Published</option><option <?=($eq['status']??'')==='Draft'?'selected':''?>>Draft</option></select></label><div><button class="btn btn-premium">Save quiz</button></div></form><?php endif?>
<div class="glass-card table-responsive mb-4"><table class="table table-dark"><tr><th>Quiz</th><th>Lesson</th><th>Questions</th><th></th></tr><?php foreach($quizzes as $q):?><tr><td><?=e($q['title'])?></td><td><?=e($q['course_title'].' / '.$q['lesson_title'])?></td><td><?=(int)$q['question_count']?></td><td><a class="btn btn-sm btn-outline-light" href="?quiz=<?=(int)$q['id']?>">Questions</a> <a class="btn btn-sm btn-outline-light" href="?edit_quiz=<?=(int)$q['id']?>">Edit</a><form class="d-inline" method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=(int)$q['id']?>"><button class="btn btn-sm btn-danger" name="action" value="delete_quiz">Delete</button></form></td></tr><?php endforeach?></table></div>
<?php if($selected):?><div class="admin-top"><h2>Questions</h2><a class="btn btn-premium" href="?quiz=<?=$selected?>&new_question=1">Add question</a></div><?php if($question||isset($_GET['new_question'])):$opts=$question?implode("\n",kids_json($question['options_json'])):'';?><form class="glass-card kids-admin-form mb-4" method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save_question"><input type="hidden" name="id" value="<?=(int)($question['id']??0)?>"><input type="hidden" name="quiz_id" value="<?=$selected?>"><label class="wide">Question<input class="form-control" name="question" value="<?=e($question['question']??'')?>" required></label><label>Options, one per line<textarea class="form-control" name="options" required><?=e($opts)?></textarea></label><label>Correct answer<input class="form-control" name="correct_answer" value="<?=e($question['correct_answer']??'')?>" required></label><label class="wide">Friendly explanation<textarea class="form-control" name="explanation" required><?=e($question['explanation']??'')?></textarea></label><label>Sort order<input class="form-control" type="number" name="sort_order" value="<?=(int)($question['sort_order']??1)?>"></label><div><button class="btn btn-premium">Save question</button></div></form><?php endif?><div class="glass-card"><?php foreach($questions as $x):?><div class="border-bottom py-3"><strong><?=e($x['question'])?></strong><div class="text-secondary">Answer: <?=e($x['correct_answer'])?></div><a href="?quiz=<?=$selected?>&edit_question=<?=(int)$x['id']?>">Edit</a></div><?php endforeach?></div><?php endif?>
<?php require_once __DIR__.'/../includes/kids-admin-footer.php';?>
