<?php
declare(strict_types=1);
require_once __DIR__.'/academy-cms-functions.php';

function render_cms_page(PDO $pdo,string $pageKey,string $theme): void { foreach(cms_sections($pdo,$pageKey) as $section) render_cms_section($pdo,$section,$theme); }
function render_cms_section(PDO $pdo,array $s,string $theme): void {
  $style='--cms-bg:'.e($s['background_color']?:'transparent').';--cms-text:'.e($s['text_color']?:'inherit');$type=$s['section_type'];$cls='cms-section cms-'.$type.' cms-'.$theme;
  if($type==='hero'){echo '<section class="'.$cls.'" style="'.$style.'"><div class="cms-container cms-hero-grid"><div class="cms-hero-copy"><span class="cms-eyebrow">'.e($s['eyebrow']).'</span><h1>'.e($s['title']).'</h1><p class="cms-subtitle">'.e($s['subtitle']).'</p><p>'.e($s['body_text']).'</p><div class="cms-actions">'.cms_button($s['button_text'],$s['button_link'],'primary').cms_button($s['secondary_button_text'],$s['secondary_button_link'],'secondary').'</div></div><div class="cms-hero-art">'.cms_media($s,'cms-hero-media').cms_avatar($s,$theme).'<div class="cms-orbit"><i></i><i></i><i></i></div></div></div></section>';return;}
  if($type==='pathways'){echo cms_open($s,$cls,$style).'<div class="cms-pathway-grid">';foreach(cms_pathways($pdo) as $p){echo '<article style="--accent:'.e($p['accent_color']?:'#6757f5').'">'.cms_media($p,'cms-card-media').'<span class="cms-path-icon">'.e($p['icon']).'</span><small>'.e($p['learner_type']).' PATHWAY</small><h3>'.e($p['name']).'</h3><p>'.e($p['description']).'</p><a href="'.e($p['button_link']).'">'.e($p['button_text']).' <b>↗</b></a></article>';}echo '</div>'.cms_close();return;}
  if($type==='courses'){echo cms_open($s,$cls,$style);$path=$theme==='kids'?'Kids':($theme==='business'?'Business':'General');echo '<div class="cms-course-grid">';foreach(cms_course_cards($pdo,$path) as $c){echo '<article style="--accent:'.e($c['accent']).'">'.cms_media($c,'cms-course-media').'<div class="cms-course-top"><span>'.e($c['icon']).'</span><small>'.e($c['category']?:$path.' Learning').'</small></div><h3>'.e($c['title']).'</h3><p>'.e($c['description']).'</p><div class="cms-meta"><span>'.e($c['level']).'</span><span>'.e($c['duration']).'</span><span>'.e($c['price_type']?:'Free').'</span></div><a href="course.php?slug='.e(urlencode($c['slug'])).'">'.e($c['button_text']?:'Start Learning').' <b>↗</b></a></article>';}echo '</div>'.cms_close();return;}
  if(in_array($type,['features','stats','testimonials'],true)){echo cms_open($s,$cls,$style).'<div class="cms-component-grid">';foreach($s['components'] as $c){echo '<article style="--accent:'.e($c['accent_color']?:'#6757f5').'">'.cms_media($c,'cms-component-media').'<span>'.e($c['icon']).'</span><small>'.e($c['subtitle']).'</small><h3>'.e($c['title']).'</h3><p>'.e($c['body_text']).'</p>'.cms_button($c['button_text'],$c['button_link'],'text').'</article>';}echo '</div>'.cms_close();return;}
  if($type==='faq'){echo cms_open($s,$cls,$style).'<div class="cms-faq-list">';foreach($s['components'] as $c)echo '<details><summary>'.e($c['title']).'<span>+</span></summary><p>'.e($c['body_text']).'</p></details>';echo '</div>'.cms_close();return;}
  if($type==='story'){echo '<section class="'.$cls.'" style="'.$style.'"><div class="cms-container cms-story-grid"><div class="cms-story-art">'.cms_media($s,'cms-story-media').cms_avatar($s,$theme).'</div><div><span class="cms-eyebrow">'.e($s['eyebrow']).'</span><h2>'.e($s['title']).'</h2><p class="cms-subtitle">'.e($s['subtitle']).'</p><p>'.e($s['body_text']).'</p>'.cms_button($s['button_text'],$s['button_link'],'primary').'</div></div></section>';return;}
  if(in_array($type,['banner','cta'],true)){echo '<section class="'.$cls.'" style="'.$style.'"><div class="cms-container cms-strip"><div><span class="cms-eyebrow">'.e($s['eyebrow']).'</span><h2>'.e($s['title']).'</h2><p>'.e($s['subtitle']).'</p></div><div class="cms-actions">'.cms_button($s['button_text'],$s['button_link'],'primary').cms_button($s['secondary_button_text'],$s['secondary_button_link'],'secondary').'</div></div></section>';return;}
  echo cms_open($s,$cls,$style).'<div class="cms-rich">'.nl2br(e($s['body_text'])).'</div>'.cms_close();
}
function cms_open(array $s,string $cls,string $style): string { return '<section class="'.$cls.'" style="'.$style.'"><div class="cms-container"><div class="cms-heading"><span class="cms-eyebrow">'.e($s['eyebrow']).'</span><h2>'.e($s['title']).'</h2><p>'.e($s['subtitle']).'</p></div>'; }
function cms_close(): string { return '</div></section>'; }
function cms_button(?string $text,?string $link,string $style): string { return ($text&&$link)?'<a class="cms-btn cms-btn-'.$style.'" href="'.e($link).'">'.e($text).'</a>':''; }
function cms_avatar(array $s,string $theme): string { if(!empty($s['avatar_path']))return '<img class="cms-avatar-img" src="'.e(site_url($s['avatar_path'])).'" alt="'.e($s['avatar_name']??'Academy guide').'">';if(!empty($s['avatar_animation']))return '<lottie-player class="cms-avatar-img" src="'.e($s['avatar_animation']).'" loop autoplay></lottie-player>';$face=$theme==='kids'?'🤖':($theme==='business'?'◈':'AI');return '<div class="cms-code-avatar cms-code-'.$theme.'"><span>'.$face.'</span><b>'.e($s['avatar_name']?:($theme==='kids'?'Robo Guide':($theme==='business'?'Business Coach':'Academy Guide'))).'</b></div>'; }
