<?php
declare(strict_types=1);
require_once __DIR__.'/functions.php';

function business_url(string $path=''): string { return site_url('business/'.ltrim($path,'/')); }
function business_json(?string $value,array $fallback=[]): array { $data=json_decode((string)$value,true);return is_array($data)?$data:$fallback; }
function business_courses(PDO $pdo,bool $published=true): array { $sql='SELECT c.*,COUNT(DISTINCT l.id) lesson_count FROM business_courses c LEFT JOIN business_lessons l ON l.course_id=c.id'.($published?" WHERE c.status='Published'":'').' GROUP BY c.id ORDER BY c.sort_order,c.id';return $pdo->query($sql)->fetchAll(); }
function business_course(PDO $pdo,int $id): ?array { $s=$pdo->prepare('SELECT * FROM business_courses WHERE id=? LIMIT 1');$s->execute([$id]);return $s->fetch()?:null; }
function business_course_slug(PDO $pdo,string $slug): ?array { $s=$pdo->prepare('SELECT * FROM business_courses WHERE slug=? LIMIT 1');$s->execute([$slug]);return $s->fetch()?:null; }
function business_lessons(PDO $pdo,int $courseId,bool $published=true): array { $s=$pdo->prepare('SELECT * FROM business_lessons WHERE course_id=?'.($published?" AND status='Published'":'').' ORDER BY sort_order,id');$s->execute([$courseId]);return $s->fetchAll(); }
function business_lesson(PDO $pdo,int $id): ?array { $s=$pdo->prepare('SELECT l.*,c.title course_title,c.slug course_slug,c.icon course_icon,c.accent_color FROM business_lessons l JOIN business_courses c ON c.id=l.course_id WHERE l.id=? LIMIT 1');$s->execute([$id]);return $s->fetch()?:null; }
function business_activities(PDO $pdo,int $lessonId): array { $s=$pdo->prepare("SELECT a.*,b.name badge_name,b.icon badge_icon FROM business_activities a LEFT JOIN business_badges b ON b.id=a.badge_id WHERE a.lesson_id=? AND a.status='Published' ORDER BY a.sort_order,a.id");$s->execute([$lessonId]);return $s->fetchAll(); }
function business_activity(PDO $pdo,int $id): ?array { $s=$pdo->prepare('SELECT a.*,c.title course_title,l.title lesson_title,b.name badge_name,b.icon badge_icon FROM business_activities a JOIN business_courses c ON c.id=a.course_id LEFT JOIN business_lessons l ON l.id=a.lesson_id LEFT JOIN business_badges b ON b.id=a.badge_id WHERE a.id=? LIMIT 1');$s->execute([$id]);return $s->fetch()?:null; }
function business_quiz(PDO $pdo,int $lessonId): ?array { $s=$pdo->prepare("SELECT q.*,b.name badge_name,b.icon badge_icon FROM business_quizzes q LEFT JOIN business_badges b ON b.id=q.badge_id WHERE q.lesson_id=? AND q.status='Published' LIMIT 1");$s->execute([$lessonId]);$q=$s->fetch();if(!$q)return null;$s=$pdo->prepare('SELECT * FROM business_quiz_questions WHERE quiz_id=? ORDER BY sort_order,id');$s->execute([$q['id']]);$q['questions']=$s->fetchAll();return $q; }
function business_progress(PDO $pdo,int $learnerId,int $courseId): array { $s=$pdo->prepare("SELECT COUNT(*) FROM business_lessons WHERE course_id=? AND status='Published'");$s->execute([$courseId]);$total=(int)$s->fetchColumn();$s=$pdo->prepare("SELECT COUNT(DISTINCT lesson_id) FROM business_progress WHERE learner_id=? AND course_id=? AND lesson_id IS NOT NULL AND status='completed'");$s->execute([$learnerId,$courseId]);$done=(int)$s->fetchColumn();return ['total'=>$total,'done'=>$done,'percent'=>$total?(int)round($done*100/$total):0]; }
function mark_business_progress(PDO $pdo,int $learnerId,int $courseId,?int $lessonId,?int $activityId,int $score=100): void { $s=$pdo->prepare("SELECT id FROM business_progress WHERE learner_id=? AND course_id=? AND lesson_id <=> ? AND activity_id <=> ? LIMIT 1");$s->execute([$learnerId,$courseId,$lessonId,$activityId]);$id=$s->fetchColumn();if($id){$pdo->prepare("UPDATE business_progress SET status='completed',score=?,completed_at=NOW() WHERE id=?")->execute([$score,$id]);}else{$pdo->prepare("INSERT INTO business_progress (learner_id,course_id,lesson_id,activity_id,status,score,completed_at) VALUES (?,?,?,?,'completed',?,NOW())")->execute([$learnerId,$courseId,$lessonId,$activityId,$score]);}$pdo->prepare("INSERT IGNORE INTO learner_pathways (learner_id,learner_type) VALUES (?,'Business')")->execute([$learnerId]); }
function award_business_badge(PDO $pdo,int $learnerId,?int $badgeId): void { if($badgeId)$pdo->prepare('INSERT IGNORE INTO business_learner_badges (learner_id,badge_id) VALUES (?,?)')->execute([$learnerId,$badgeId]); }
function business_course_complete(PDO $pdo,int $learnerId,int $courseId): bool { $p=business_progress($pdo,$learnerId,$courseId);return $p['total']>0&&$p['percent']===100; }
function issue_business_certificate(PDO $pdo,int $learnerId,int $courseId): ?array { if(!business_course_complete($pdo,$learnerId,$courseId))return null;$code='BIZ-'.date('Y').'-'.strtoupper(substr(bin2hex(random_bytes(6)),0,12));$pdo->prepare('INSERT IGNORE INTO business_certificates (learner_id,course_id,certificate_code) VALUES (?,?,?)')->execute([$learnerId,$courseId,$code]);$s=$pdo->prepare('SELECT * FROM business_certificates WHERE learner_id=? AND course_id=?');$s->execute([$learnerId,$courseId]);return $s->fetch()?:null; }
function business_upload(string $field,array $types): ?string { if(empty($_FILES[$field]['tmp_name'])||!is_uploaded_file($_FILES[$field]['tmp_name']))return null;$allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/gif'=>'gif','image/webp'=>'webp','video/mp4'=>'mp4','application/json'=>'json','application/pdf'=>'pdf','text/csv'=>'csv','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'=>'xlsx','application/vnd.openxmlformats-officedocument.wordprocessingml.document'=>'docx'];$mime=(new finfo(FILEINFO_MIME_TYPE))->file($_FILES[$field]['tmp_name']);if(!isset($allowed[$mime])||!in_array($allowed[$mime],$types,true)||(int)$_FILES[$field]['size']>15*1024*1024)throw new RuntimeException('Unsupported file or file larger than 15 MB.');$dir=dirname(__DIR__).'/assets/uploads/business';if(!is_dir($dir))mkdir($dir,0755,true);$name=bin2hex(random_bytes(10)).'.'.$allowed[$mime];if(!move_uploaded_file($_FILES[$field]['tmp_name'],$dir.'/'.$name))throw new RuntimeException('Upload could not be saved.');return 'assets/uploads/business/'.$name; }
function business_visual(string $type='coach'): string { $icons=['coach'=>'◈','dashboard'=>'▥','marketing'=>'↗','automation'=>'⚙','chatbot'=>'◎','finance'=>'$','security'=>'◇','ecommerce'=>'▣','productivity'=>'✓','reports'=>'▤'];$icon=$icons[$type]??'AI';return '<div class="biz-scene" data-scene="'.e($type).'"><div class="office-grid"></div><div class="coach-avatar"><i></i><span>'.$icon.'</span><b>Business AI Coach</b></div><div class="biz-screen"><div class="screen-head"><em></em><em></em><em></em></div><div class="mini-kpis"><strong>+24%</strong><strong>3.2h</strong><strong>92%</strong></div><div class="mini-chart"><i></i><i></i><i></i><i></i><i></i></div></div><span class="signal signal-a">INSIGHT</span><span class="signal signal-b">ACTION</span></div>'; }
