<?php
declare(strict_types=1);

function slugify(string $text): string { $slug=strtolower((string)preg_replace('/[^a-z0-9]+/i','-',trim($text))); return trim($slug,'-') ?: 'item-'.time(); }
function academy_categories(PDO $pdo=null): array { if(!$pdo) return []; return $pdo->query("SELECT * FROM lms_categories WHERE status='active' ORDER BY name")->fetchAll(); }
function get_courses(PDO $pdo,bool $publishedOnly=true): array { $sql="SELECT c.*,cat.name AS category_name,COUNT(l.id) AS lesson_count FROM lms_courses c LEFT JOIN lms_categories cat ON cat.id=c.category_id LEFT JOIN lms_modules m ON m.course_id=c.id LEFT JOIN lms_lessons l ON l.module_id=m.id"; if($publishedOnly){$sql.=" WHERE c.status='Published'";} $sql.=" GROUP BY c.id ORDER BY c.created_at DESC"; return $pdo->query($sql)->fetchAll(); }
function get_course(PDO $pdo,int $id): ?array { $s=$pdo->prepare('SELECT c.*,cat.name AS category_name FROM lms_courses c LEFT JOIN lms_categories cat ON cat.id=c.category_id WHERE c.id=:id LIMIT 1'); $s->execute([':id'=>$id]); $r=$s->fetch(); return $r?:null; }
function get_course_by_slug(PDO $pdo,string $slug): ?array { $s=$pdo->prepare('SELECT c.*,cat.name AS category_name FROM lms_courses c LEFT JOIN lms_categories cat ON cat.id=c.category_id WHERE c.slug=:slug LIMIT 1'); $s->execute([':slug'=>$slug]); $r=$s->fetch(); return $r?:null; }
function get_course_modules(PDO $pdo,int $courseId): array { $s=$pdo->prepare('SELECT * FROM lms_modules WHERE course_id=:c ORDER BY sort_order,id'); $s->execute([':c'=>$courseId]); return $s->fetchAll(); }
function get_course_lessons(PDO $pdo,int $courseId): array { $s=$pdo->prepare('SELECT l.*,m.title AS module_title,m.course_id FROM lms_lessons l JOIN lms_modules m ON m.id=l.module_id WHERE m.course_id=:c AND l.status="Published" ORDER BY m.sort_order,l.sort_order,l.id'); $s->execute([':c'=>$courseId]); return $s->fetchAll(); }
function get_lesson(PDO $pdo,int $lessonId): ?array { $s=$pdo->prepare('SELECT l.*,m.title AS module_title,m.course_id,c.title AS course_title,c.slug AS course_slug FROM lms_lessons l JOIN lms_modules m ON m.id=l.module_id JOIN lms_courses c ON c.id=m.course_id WHERE l.id=:id LIMIT 1'); $s->execute([':id'=>$lessonId]); $r=$s->fetch(); return $r?:null; }
function enroll_learner(PDO $pdo,int $learnerId,int $courseId): void { $s=$pdo->prepare('INSERT IGNORE INTO lms_enrollments (learner_id,course_id) VALUES (:l,:c)'); $s->execute([':l'=>$learnerId,':c'=>$courseId]); }
function is_enrolled(PDO $pdo,int $learnerId,int $courseId): bool { $s=$pdo->prepare('SELECT id FROM lms_enrollments WHERE learner_id=:l AND course_id=:c LIMIT 1'); $s->execute([':l'=>$learnerId,':c'=>$courseId]); return (bool)$s->fetchColumn(); }
function mark_lesson_complete(PDO $pdo,int $learnerId,int $courseId,int $lessonId): void { enroll_learner($pdo,$learnerId,$courseId); $s=$pdo->prepare('INSERT IGNORE INTO lms_lesson_progress (learner_id,course_id,lesson_id) VALUES (:l,:c,:lesson)'); $s->execute([':l'=>$learnerId,':c'=>$courseId,':lesson'=>$lessonId]); }
function course_progress(PDO $pdo,int $learnerId,int $courseId): array { $s=$pdo->prepare('SELECT COUNT(*) FROM lms_lessons l JOIN lms_modules m ON m.id=l.module_id WHERE m.course_id=:c AND l.status="Published"'); $s->execute([':c'=>$courseId]); $total=(int)$s->fetchColumn(); $s=$pdo->prepare('SELECT COUNT(*) FROM lms_lesson_progress WHERE learner_id=:l AND course_id=:c'); $s->execute([':l'=>$learnerId,':c'=>$courseId]); $done=(int)$s->fetchColumn(); $percent=$total? (int)round(($done/$total)*100):0; return ['total'=>$total,'done'=>$done,'pending'=>max(0,$total-$done),'percent'=>$percent]; }
function learner_enrollments(PDO $pdo,int $learnerId): array { $s=$pdo->prepare('SELECT c.*,cat.name AS category_name,e.enrolled_at FROM lms_enrollments e JOIN lms_courses c ON c.id=e.course_id LEFT JOIN lms_categories cat ON cat.id=c.category_id WHERE e.learner_id=:l ORDER BY e.enrolled_at DESC'); $s->execute([':l'=>$learnerId]); $rows=$s->fetchAll(); foreach($rows as &$r){$r['progress']=course_progress($pdo,$learnerId,(int)$r['id']);} return $rows; }
function get_quiz(PDO $pdo,int $courseId): ?array { $s=$pdo->prepare('SELECT * FROM lms_quizzes WHERE course_id=:c LIMIT 1'); $s->execute([':c'=>$courseId]); $q=$s->fetch(); if(!$q)return null; $s=$pdo->prepare('SELECT * FROM lms_quiz_questions WHERE quiz_id=:q ORDER BY sort_order,id'); $s->execute([':q'=>$q['id']]); $q['questions']=$s->fetchAll(); return $q; }
function latest_quiz_attempt(PDO $pdo,int $learnerId,int $courseId): ?array { $s=$pdo->prepare('SELECT * FROM lms_quiz_attempts WHERE learner_id=:l AND course_id=:c ORDER BY created_at DESC LIMIT 1'); $s->execute([':l'=>$learnerId,':c'=>$courseId]); $r=$s->fetch(); return $r?:null; }
function eligible_for_certificate(PDO $pdo,int $learnerId,int $courseId): bool { $p=course_progress($pdo,$learnerId,$courseId); $a=latest_quiz_attempt($pdo,$learnerId,$courseId); return $p['total']>0 && $p['percent']>=100 && $a && (int)$a['passed']===1; }
function issue_certificate(PDO $pdo,int $learnerId,int $courseId): ?array { if(!eligible_for_certificate($pdo,$learnerId,$courseId)) return null; $s=$pdo->prepare('SELECT * FROM lms_certificates WHERE learner_id=:l AND course_id=:c LIMIT 1'); $s->execute([':l'=>$learnerId,':c'=>$courseId]); if($r=$s->fetch()) return $r; $cert='MDTA-'.date('Y').'-'.strtoupper(substr(bin2hex(random_bytes(5)),0,10)); $code=strtoupper(substr(hash('sha256',$cert.$learnerId.$courseId),0,12)); $s=$pdo->prepare('INSERT INTO lms_certificates (learner_id,course_id,certificate_id,verification_code) VALUES (:l,:c,:cert,:code)'); $s->execute([':l'=>$learnerId,':c'=>$courseId,':cert'=>$cert,':code'=>$code]); $s=$pdo->prepare('SELECT * FROM lms_certificates WHERE certificate_id=:cert'); $s->execute([':cert'=>$cert]); return $s->fetch(); }
function lms_admin_counts(PDO $pdo): array { return ['Total courses'=>(int)$pdo->query('SELECT COUNT(*) FROM lms_courses')->fetchColumn(),'Published courses'=>(int)$pdo->query("SELECT COUNT(*) FROM lms_courses WHERE status='Published'")->fetchColumn(),'Total learners'=>(int)$pdo->query('SELECT COUNT(*) FROM learners')->fetchColumn(),'Active learners'=>(int)$pdo->query('SELECT COUNT(DISTINCT learner_id) FROM lms_enrollments')->fetchColumn(),'Total enrollments'=>(int)$pdo->query('SELECT COUNT(*) FROM lms_enrollments')->fetchColumn(),'Completed courses'=>(int)$pdo->query("SELECT COUNT(*) FROM lms_enrollments WHERE status='completed'")->fetchColumn(),'Certificates issued'=>(int)$pdo->query('SELECT COUNT(*) FROM lms_certificates')->fetchColumn(),'Average quiz score'=>(int)$pdo->query('SELECT COALESCE(AVG(percentage),0) FROM lms_quiz_attempts')->fetchColumn()]; }